export enum StreamingProvider {
    disneyPlus = 'disneyPlus',
    netflix = 'netflix',
    amazonPrime = 'amazonPrime',
    hbo = 'hbo',
    hulu = 'hulu',
    appleTv = 'appleTv',
    peacock = 'peacock',
    paramountPlus = 'paramountPlus',
    youtube = 'youtube',
    doramasGo = 'doramasGo',
    rakutenViki = 'rakutenViki',
    HiTV = 'HiTV',
    weTV = 'weTV',
    youku = 'youku',
    iqiyi = 'iqiyi',
    doramasPrincess = 'doramasPrincess',
    doramasflix = 'doramasflix',
}